spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20
            redis-rate-limiter.burstCapacity: 40
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@ipKeyResolver}"
